export interface PromptItem {
  id: string;
  nameZh: string;
  nameEn: string;
  kind: 'ninja' | 'house' | 'ui';
  phase: string;
  number: number | null;
  visualHint: string;
  promptZh: string;
  promptEn: string;
  negative: string;
}

export const BASE_STYLE_PREFIX =
  'Modern ukiyo-e character illustration as the main subject, ink wash painting (sumi-e) background depicting night atmosphere, with minimal neon accents or gold foil (kintsugi) highlights on key skill elements and faction crests. Palette: ink black and deep indigo for base, with restrained neon/gold accents. Top 12% and bottom 22% of the composition reserved as plain color margins for text overlay, no visual elements in those regions. Original artwork, not imitating any existing published illustration.';

export const STANDARD_NEGATIVE =
  'text, watermark, logo, typography, border, frame, extra limbs, low quality, blurry, deformed hands, signature, cropped';

export const PROMPTS: PromptItem[] = [
  // ==========================================
  // 1. 密探 (Spy 1-6) - 视觉提示：暗处窥视、卷轴、眼睛（水墨夜色中一点金箔眼）
  // ==========================================
  {
    id: 'spy-1',
    nameZh: '密探 1',
    nameEn: 'Spy 1',
    kind: 'ninja',
    phase: 'spy',
    number: 1,
    visualHint: '暗处窥视、卷轴、眼睛（水墨夜色中一点金箔眼）',
    promptZh: '密探隐匿于竹帘阴影中，半展开绝密卷轴，水墨夜色中唯有一只眼睛闪烁着金色眼眸与金箔微光。',
    promptEn: `${BASE_STYLE_PREFIX} Subject: A hooded ninja spy crouching behind a dark bamboo lattice screen in an ink-wash night chamber, carefully unrolling an ancient silk scroll. One piercing eye gleams through a narrow gap with a bright gold foil (kintsugi) fleck iris, surrounded by deep sumi-e indigo shadows. Vertical 2:3 composition.`,
    negative: STANDARD_NEGATIVE,
  },
  {
    id: 'spy-2',
    nameZh: '密探 2',
    nameEn: 'Spy 2',
    kind: 'ninja',
    phase: 'spy',
    number: 2,
    visualHint: '暗处窥视、梁上垂卷、水墨微光中的金箔眼',
    promptZh: '密探倒伏于木梁暗角，向下垂放探秘卷轴，浓墨阴影中泛起金箔眼眸的冷峻光芒。',
    promptEn: `${BASE_STYLE_PREFIX} Subject: A stealthy ninja scout poised atop high wooden rafters in a dimly lit temple at midnight, dangling an unrolled espionage scroll into darkness. A subtle single golden foil eye shines sharply in the deep indigo ink wash silhouette. Vertical 2:3 composition.`,
    negative: STANDARD_NEGATIVE,
  },
  {
    id: 'spy-3',
    nameZh: '密探 3',
    nameEn: 'Spy 3',
    kind: 'ninja',
    phase: 'spy',
    number: 3,
    visualHint: '暗处窥视、林木阴影、手握卷轴与微光利刃',
    promptZh: '密探侧身隐于枯树浓墨枝桠之后，单手紧握暗金封漆卷轴，夜雾中仅见一点金箔眼眸锐利逼人。',
    promptEn: `${BASE_STYLE_PREFIX} Subject: A solitary ninja spy partially concealed behind twisting ink-painted tree branches under a moonless sky, clutching an ornate scroll sealed with kintsugi gold wax. A glowing gold-foil eye cuts through the dark indigo mist. Vertical 2:3 composition.`,
    negative: STANDARD_NEGATIVE,
  },
  {
    id: 'spy-4',
    nameZh: '密探 4',
    nameEn: 'Spy 4',
    kind: 'ninja',
    phase: 'spy',
    number: 4,
    visualHint: '暗处窥视、飞檐倒挂、卷轴入怀与金眸凝视',
    promptZh: '密探悬吊于飞檐瓦片阴影中，将抄录的密卷收纳于怀，夜色如墨，唯有单眼如金箔明灯般注视下方。',
    promptEn: `${BASE_STYLE_PREFIX} Subject: An agile ninja spy clinging inverted beneath tiled temple eaves, slipping a freshly inked cipher scroll into a black silk sash. A brilliant pinpoint gold foil eye glints with focused precision against velvety sumi-e dark tones. Vertical 2:3 composition.`,
    negative: STANDARD_NEGATIVE,
  },
  {
    id: 'spy-5',
    nameZh: '密探 5',
    nameEn: 'Spy 5',
    kind: 'ninja',
    phase: 'spy',
    number: 5,
    visualHint: '暗处窥视、烟幕破影、双手展卷与金光凝瞳',
    promptZh: '密探隐于淡淡水墨烟雾之后，双手展开密报卷轴，在深沉靛蓝与水墨中透出一抹极简的金箔眼神。',
    promptEn: `${BASE_STYLE_PREFIX} Subject: A shadowy ninja spy emerging through soft drifting charcoal smoke, holding an open parchment deciphering tactical symbols. A vivid fleck of pure gold foil adorns the spy's watchful eye amidst atmospheric indigo ink wash. Vertical 2:3 composition.`,
    negative: STANDARD_NEGATIVE,
  },
  {
    id: 'spy-6',
    nameZh: '密探 6',
    nameEn: 'Spy 6',
    kind: 'ninja',
    phase: 'spy',
    number: 6,
    visualHint: '暗处窥视、雨夜凭栏、卷轴墨迹与金瞳远眺',
    promptZh: '密探身披蓑衣夜行衣立于雨夜楼阁阴影，一手按卷，一侧金箔眼瞳穿透水墨雨丝凝望远方。',
    promptEn: `${BASE_STYLE_PREFIX} Subject: A stoic ninja spy standing motionless in fine diagonal ink-wash night rain beside a weathered wooden balustrade, holding an antique scroll. A luminous kintsugi gold foil eye gleams quietly in the deep indigo monochrome gloom. Vertical 2:3 composition.`,
    negative: STANDARD_NEGATIVE,
  },

  // ==========================================
  // 2. 隐士 (Mystic 1-6) - 视觉提示：占卜、牌阵、月光
  // ==========================================
  {
    id: 'mystic-1',
    nameZh: '隐士 1',
    nameEn: 'Mystic 1',
    kind: 'ninja',
    phase: 'mystic',
    number: 1,
    visualHint: '占卜、牌阵、月光',
    promptZh: '神秘隐士双掌微悬，三张泛着微光的占卜符牌在幽冷月光下环绕成弧形，水墨夜雾氤氲。',
    promptEn: `${BASE_STYLE_PREFIX} Subject: A mystical hermit diviner in flowing sumi-e robes, hands hovering over an ethereal crescent arc of three floating omen cards. Pale silver moonlight spills from an indigo sky, illuminating delicate gold-foil astrological glyphs on the cards. Vertical 2:3 composition.`,
    negative: STANDARD_NEGATIVE,
  },
  {
    id: 'mystic-2',
    nameZh: '隐士 2',
    nameEn: 'Mystic 2',
    kind: 'ninja',
    phase: 'mystic',
    number: 2,
    visualHint: '占卜、星图牌阵、幽暗月晕',
    promptZh: '隐士盘坐于榻榻米上，面前排列着悬空的玄奥占卜牌阵，清冷明月在墨色夜空中洒下静谧银辉。',
    promptEn: `${BASE_STYLE_PREFIX} Subject: A meditative mystic seated in quiet contemplation, surrounded by a geometric circle of levitating divination paper charms. A massive, soft-edged ink-wash full moon glows above, with faint neon indigo lines tracing cosmic alignments. Vertical 2:3 composition.`,
    negative: STANDARD_NEGATIVE,
  },
  {
    id: 'mystic-3',
    nameZh: '隐士 3',
    nameEn: 'Mystic 3',
    kind: 'ninja',
    phase: 'mystic',
    number: 3,
    visualHint: '占卜、青烟化牌、轩窗月色',
    promptZh: '隐士香炉青烟缕缕升腾并化作悬浮牌阵，月光透过障子纸窗，金箔与银白光点交织于指尖。',
    promptEn: `${BASE_STYLE_PREFIX} Subject: An esoteric mystic releasing thin tendrils of incense smoke from a bronze burner that crystallize into floating cards. Cool moonlight filters through a paper screen, with delicate gold foil kintsugi veins glimmering on the cards. Vertical 2:3 composition.`,
    negative: STANDARD_NEGATIVE,
  },
  {
    id: 'mystic-4',
    nameZh: '隐士 4',
    nameEn: 'Mystic 4',
    kind: 'ninja',
    phase: 'mystic',
    number: 4,
    visualHint: '占卜、墨水古盆、映月牌影',
    promptZh: '隐士俯瞰一泓水墨古盆，水中倒映月影与漂浮的占卜法牌，夜色深沉，神情超脱尘世。',
    promptEn: `${BASE_STYLE_PREFIX} Subject: A wise mystic looking down into an antique stone water basin reflecting a shimmering crescent moon and floating omen cards. Swirls of ink wash night water with fine gold-foil flecks on the card borders. Vertical 2:3 composition.`,
    negative: STANDARD_NEGATIVE,
  },
  {
    id: 'mystic-5',
    nameZh: '隐士 5',
    nameEn: 'Mystic 5',
    kind: 'ninja',
    phase: 'mystic',
    number: 5,
    visualHint: '占卜、法铃与流光牌阵、皎洁孤月',
    promptZh: '隐士手持摇晃的铜质法铃，流转的占卜牌阵如光带环绕腕间，皎洁明月破墨云而出。',
    promptEn: `${BASE_STYLE_PREFIX} Subject: A robed oracle raising a small ceremonial bronze bell, surrounded by a swirling spiral of illuminated prediction cards. Pure silver moonlight pierces deep indigo ink clouds, with subtle neon gold trim on the robes. Vertical 2:3 composition.`,
    negative: STANDARD_NEGATIVE,
  },
  {
    id: 'mystic-6',
    nameZh: '隐士 6',
    nameEn: 'Mystic 6',
    kind: 'ninja',
    phase: 'mystic',
    number: 6,
    visualHint: '占卜、悬崖迎风展阵、冷月长空',
    promptZh: '隐士伫立于夜风呼啸的孤峰之巅，占卜牌阵随夜风徐徐展开，万丈夜空一轮寒月高悬。',
    promptEn: `${BASE_STYLE_PREFIX} Subject: A grand mystic standing on a windswept mountain precipice, wide sleeves billowing as an expansive arc of divination cards fans out into the night. A stark white ink-wash moon shines overhead against deep black-indigo space. Vertical 2:3 composition.`,
    negative: STANDARD_NEGATIVE,
  },

  // ==========================================
  // 3. 骗徒 (Tricksters: 1-6 种)
  // ==========================================
  {
    id: 'shapeshifter-1',
    nameZh: '百变者 1',
    nameEn: 'Shapeshifter 1',
    kind: 'ninja',
    phase: 'trickster',
    number: 1,
    visualHint: '面具、镜像、双影',
    promptZh: '百变者手握能面半遮容颜，身侧是一面碎裂的青铜立镜，水墨夜色中映照出两道截然不同的异色身影。',
    promptEn: `${BASE_STYLE_PREFIX} Subject: An elusive shapeshifter ninja holding a blank white Noh mask half-covering their face, positioned beside a tall fractured antique bronze mirror. The broken glass reflects a dual, shifting shadow figure in neon indigo and ink wash split silhouettes. Vertical 2:3 composition.`,
    negative: STANDARD_NEGATIVE,
  },
  {
    id: 'grave_digger-2',
    nameZh: '掘墓人 2',
    nameEn: 'Grave Digger 2',
    kind: 'ninja',
    phase: 'trickster',
    number: 2,
    visualHint: '掘土、枯骨、残牌',
    promptZh: '掘墓人跪于长满青苔的荒冢前，身旁铁铲掘开新土，枯骨与残破的古旧卡牌在昏暗油灯微光下重见天日。',
    promptEn: `${BASE_STYLE_PREFIX} Subject: A grim grave digger ninja kneeling in a forgotten mossy graveyard at night, an iron spade planted in dark churned earth. A small dim lantern illuminates weathered skeletal remains and unearthed antique torn playing cards with gold-foil cracks. Vertical 2:3 composition.`,
    negative: STANDARD_NEGATIVE,
  },
  {
    id: 'troublemaker-3',
    nameZh: '捣蛋鬼 3',
    nameEn: 'Troublemaker 3',
    kind: 'ninja',
    phase: 'trickster',
    number: 3,
    visualHint: '掀桌、喧哗、火把',
    promptZh: '捣蛋鬼在茶馆喧闹声中猛然掀翻木桌，茶盏与骰子凌空飞溅，手中挥舞着迸发火星的明亮火把，动感水墨四溢。',
    promptEn: `${BASE_STYLE_PREFIX} Subject: A chaotic troublemaker ninja violently overturning a heavy wooden tavern table in dynamic perspective. Flying cups, dice, and splattering black ink drops fill the air as the character swings a blazing ember-sparking torch with wild neon-red sparks. Vertical 2:3 composition.`,
    negative: STANDARD_NEGATIVE,
  },
  {
    id: 'spirit_merchant-4',
    nameZh: '商人 4',
    nameEn: 'Spirit Merchant 4',
    kind: 'ninja',
    phase: 'trickster',
    number: 4,
    visualHint: '天平、钱袋、讨价',
    promptZh: '行踪神秘的灵魂商人托起古铜小天平，托盘一侧放着金箔标记，另一侧悬着沉甸甸的锦囊钱袋，夜雾中讨价还价。',
    promptEn: `${BASE_STYLE_PREFIX} Subject: An enigmatic spirit merchant in a dark bamboo conical hat holding up an ornate handheld brass balance scale. One pan weighs a kintsugi gold-foiled circular honor token, while the other balances an embroidered velvet coin purse in mystical misty darkness. Vertical 2:3 composition.`,
    negative: STANDARD_NEGATIVE,
  },
  {
    id: 'thief-5',
    nameZh: '盗贼 5',
    nameEn: 'Thief 5',
    kind: 'ninja',
    phase: 'trickster',
    number: 5,
    visualHint: '暗手、令牌、金袋',
    promptZh: '黑夜中伸出一只敏捷矫健的暗影之手，悄然从华丽锦缎腰带上抽走一枚金箔荣誉令牌，旁边系着沉重金袋。',
    promptEn: `${BASE_STYLE_PREFIX} Subject: A nimble phantom thief in midnight stealth gear, one gloved hand deftly slipping a glowing gold-foil circular honor token from an opponent's silk sash, clutching a heavy leather pouch in the other hand. Dramatic sumi-e smoke trails. Vertical 2:3 composition.`,
    negative: STANDARD_NEGATIVE,
  },
  {
    id: 'judge-6',
    nameZh: '裁判 6',
    nameEn: 'Judge 6',
    kind: 'ninja',
    phase: 'trickster',
    number: 6,
    visualHint: '高举判词、火印、裁决',
    promptZh: '威严冷峻的审判官高举写满水墨誓词的裁决卷轴，一枚燃烧着烈火红光的朱红火印重重盖下，气势庄严。',
    promptEn: `${BASE_STYLE_PREFIX} Subject: An imposing masked judge raising a grand scroll of solemn judicial decree high overhead with both hands, pressing down a fiery crimson flame seal stamp onto paper. Radiant vermilion embers and dramatic black ink splash composition. Vertical 2:3 composition.`,
    negative: STANDARD_NEGATIVE,
  },

  // ==========================================
  // 4. 刺客 (Blind Assassin 1-6) - 视觉提示：兜帽、双刀、阴影（不露眼）
  // ==========================================
  {
    id: 'blind_assassin-1',
    nameZh: '刺客 1',
    nameEn: 'Blind Assassin 1',
    kind: 'ninja',
    phase: 'blind_assassin',
    number: 1,
    visualHint: '兜帽、双刀、阴影（不露眼）',
    promptZh: '冷酷刺客深垂兜帽完全遮蔽双眼，胸前十字交叉双柄短刀，静伏于无边水墨夜色阴影之中。',
    promptEn: `${BASE_STYLE_PREFIX} Subject: A lethal blind assassin shrouded in a deep cloth cowl completely veiling the upper face and eyes in impenetrable black shadow. Twin Japanese tanto daggers are held crossed tightly in front of the chest, edge gleaming with a faint cold blade highlight. Vertical 2:3 composition.`,
    negative: STANDARD_NEGATIVE,
  },
  {
    id: 'blind_assassin-2',
    nameZh: '刺客 2',
    nameEn: 'Blind Assassin 2',
    kind: 'ninja',
    phase: 'blind_assassin',
    number: 2,
    visualHint: '兜帽遮目、反手双刃、低身疾步',
    promptZh: '刺客兜帽低垂不露双眼，双手反握锋利短刀贴地滑行，身后拖曳出漆黑水墨残影。',
    promptEn: `${BASE_STYLE_PREFIX} Subject: A deadly assassin lunging forward in a low sliding stance across tatami mats, face entirely obscured by a shadowed hood. Holding twin blades in reverse grip with razor-sharp gold-etched edges cutting through ink-wash darkness. Vertical 2:3 composition.`,
    negative: STANDARD_NEGATIVE,
  },
  {
    id: 'blind_assassin-3',
    nameZh: '刺客 3',
    nameEn: 'Blind Assassin 3',
    kind: 'ninja',
    phase: 'blind_assassin',
    number: 3,
    visualHint: '兜帽无面、从天而降、双刀直指',
    promptZh: '刺客从屋梁幽暗高处无声垂落，兜帽下唯有无底深渊，双刀垂直向下锁定猎物。',
    promptEn: `${BASE_STYLE_PREFIX} Subject: A hooded assassin descending silently from high wooden rafters, fabric cowl casting complete blackness over facial features. Twin daggers pointed straight downward, cloaked in billows of deep indigo calligraphic brushstroke smoke. Vertical 2:3 composition.`,
    negative: STANDARD_NEGATIVE,
  },
  {
    id: 'blind_assassin-4',
    nameZh: '刺客 4',
    nameEn: 'Blind Assassin 4',
    kind: 'ninja',
    phase: 'blind_assassin',
    number: 4,
    visualHint: '兜帽盲客、回旋双刀、墨气斩裂',
    promptZh: '刺客被深色头巾与兜帽严实遮盖双目，挥舞双刀划开夜雾，带起弧形墨线与金色刀光。',
    promptEn: `${BASE_STYLE_PREFIX} Subject: A blindfolded assassin executing a swift spinning double-dagger slash through thick night fog. The head is concealed in a dark hood with no eyes visible, while the twin blade arcs carve glowing gold-leaf tracer trails in the air. Vertical 2:3 composition.`,
    negative: STANDARD_NEGATIVE,
  },
  {
    id: 'blind_assassin-5',
    nameZh: '刺客 5',
    nameEn: 'Blind Assassin 5',
    kind: 'ninja',
    phase: 'blind_assassin',
    number: 5,
    visualHint: '兜帽隐匿、石灯停驻、滴血双刃',
    promptZh: '刺客蹲伏于庭院石灯笼顶部，兜帽遮掩全貌，双刀刃口滴落墨色水珠，散发森然杀气。',
    promptEn: `${BASE_STYLE_PREFIX} Subject: A menacing assassin perched crouched atop an ancient mossy stone garden lantern, face lost in pitch-black shadow under a heavy cowl. Twin knives held ready, ink-wash droplets dripping from the polished metallic points. Vertical 2:3 composition.`,
    negative: STANDARD_NEGATIVE,
  },
  {
    id: 'blind_assassin-6',
    nameZh: '刺客 6',
    nameEn: 'Blind Assassin 6',
    kind: 'ninja',
    phase: 'blind_assassin',
    number: 6,
    visualHint: '兜帽极影、竹林伫立、双刃蓄势',
    promptZh: '刺客静立于夜间狂风摇曳的竹海深处，厚重兜帽下不见眉目，双刀藏于臂后，杀机暗涌。',
    promptEn: `${BASE_STYLE_PREFIX} Subject: A silent blind assassin standing motionless amid a storm of dark bamboo stalks at midnight. The long hood completely conceals any eyes, twin blades gleaming subtly behind the forearms with restrained gold kintsugi foil highlights. Vertical 2:3 composition.`,
    negative: STANDARD_NEGATIVE,
  },

  // ==========================================
  // 5. 上忍 (Shinobi 1-6) - 视觉提示：屋顶、绳索、忍具（可露眼）
  // ==========================================
  {
    id: 'shinobi-1',
    nameZh: '上忍 1',
    nameEn: 'Shinobi 1',
    kind: 'ninja',
    phase: 'shinobi',
    number: 1,
    visualHint: '屋顶、绳索、忍具（可露眼）',
    promptZh: '敏捷上忍疾驰于传统青瓦屋脊之上，手握收拢的飞爪绳索，锐利坚毅的双眼直视前方，夜风扬起额带。',
    promptEn: `${BASE_STYLE_PREFIX} Subject: An elite shinobi ninja sprinting dynamically across curved traditional roof tiles at night. Holding a coiled grappling rope and iron hook, with determined, fiercely visible eyes gazing forward above a dark ninja face mask. Flying headband ribbons. Vertical 2:3 composition.`,
    negative: STANDARD_NEGATIVE,
  },
  {
    id: 'shinobi-2',
    nameZh: '上忍 2',
    nameEn: 'Shinobi 2',
    kind: 'ninja',
    phase: 'shinobi',
    number: 2,
    visualHint: '屋脊蹲踞、旋转手里剑、警惕锐目',
    promptZh: '上忍单膝蹲伏于屋顶正脊兽首旁，指间飞转三尖苦无手里剑，一双明亮警惕的眼睛扫视整片城池。',
    promptEn: `${BASE_STYLE_PREFIX} Subject: A high shinobi crouching balanced on a rooftop ridge beside an ornamental ridge tile gargoyle, spinning a three-pronged metallic shuriken. Clear, alert eyes glowing with tactical focus under a starry indigo sumi-e night sky. Vertical 2:3 composition.`,
    negative: STANDARD_NEGATIVE,
  },
  {
    id: 'shinobi-3',
    nameZh: '上忍 3',
    nameEn: 'Shinobi 3',
    kind: 'ninja',
    phase: 'shinobi',
    number: 3,
    visualHint: '凌空飞跃、抛掷忍绳、银光暗器',
    promptZh: '上忍在两座漆黑楼阁屋顶间凌空飞跃，抛出飞檐绳锁，指缝间夹着数枚银光闪耀的穿云忍针，目光坚定。',
    promptEn: `${BASE_STYLE_PREFIX} Subject: A master shinobi leaping across a wide moonlit gap between adjacent tiled pavilions, casting a trailing climbing rope. Visible focused eyes locked onto the landing, clutching gleaming silver throwing spikes. Vertical 2:3 composition.`,
    negative: STANDARD_NEGATIVE,
  },
  {
    id: 'shinobi-4',
    nameZh: '上忍 4',
    nameEn: 'Shinobi 4',
    kind: 'ninja',
    phase: 'shinobi',
    number: 4,
    visualHint: '瓦当边缘、备掷烟雾弹、冷峻审视',
    promptZh: '上忍伏在檐角瓦当边，单手扣住特制黑火药烟雾弹，目光如鹰隼般俯瞰下方守卫严密的高宅深院。',
    promptEn: `${BASE_STYLE_PREFIX} Subject: A veteran shinobi poised at the decorative corner of a pagoda roof, holding a smoke grenade orb wrapped in gold wire. Sharp, calculating human eyes survey the castle courtyard below through drifting ink mist. Vertical 2:3 composition.`,
    negative: STANDARD_NEGATIVE,
  },
  {
    id: 'shinobi-5',
    nameZh: '上忍 5',
    nameEn: 'Shinobi 5',
    kind: 'ninja',
    phase: 'shinobi',
    number: 5,
    visualHint: '塔顶金鸡独立、钢丝绷紧、随风飘带',
    promptZh: '上忍单足立于宝塔屋顶避雷铁尖，十指间扯紧半透明的致命钢丝忍具，冷冽双眸在夜风中凝视下方。',
    promptEn: `${BASE_STYLE_PREFIX} Subject: A peerless shinobi balanced on one foot atop a tall temple roof spire against a massive indigo night sky. Taut tactical wire glints between outstretched fingers, with fierce expressive eyes visible above the cowl. Vertical 2:3 composition.`,
    negative: STANDARD_NEGATIVE,
  },
  {
    id: 'shinobi-6',
    nameZh: '上忍 6',
    nameEn: 'Shinobi 6',
    kind: 'ninja',
    phase: 'shinobi',
    number: 6,
    visualHint: '屋顶滑降、锁镰锁链、烈火般的视线',
    promptZh: '上忍顺着倾斜瓦面敏捷滑步，手中锁镰的铁链如银蛇乱舞，露出的双目中蕴藏着百炼之忍的威光。',
    promptEn: `${BASE_STYLE_PREFIX} Subject: A formidable shinobi sliding down the steep pitch of ceramic roof tiles, swinging a traditional kusarigama sickle and weighted chain. Striking, resolute eyes shining intensely with warrior spirit in the dark. Vertical 2:3 composition.`,
    negative: STANDARD_NEGATIVE,
  },

  // ==========================================
  // 6. 特殊牌：还施者 (Mirror Monk), 殉道者 (Martyr), 大将军 (Mastermind)
  // ==========================================
  {
    id: 'mirror_monk',
    nameZh: '还施者',
    nameEn: 'Mirror Monk',
    kind: 'ninja',
    phase: 'react',
    number: null,
    visualHint: '铜镜、回击、禅意',
    promptZh: '宝相庄严的禅僧手持八角铜镜，镜面泛起空灵涟漪反弹夜袭的墨刃杀气，神色慈悲淡泊，充满禅意。',
    promptEn: `${BASE_STYLE_PREFIX} Subject: A serene monk in dark indigo meditative robes holding a polished octagonal antique bronze mirror facing forward. The mirror surface ripples with a radiant zen reflection that deflects a shadowy strike with golden kintsugi shockwaves. Calm, tranquil expression. Vertical 2:3 composition.`,
    negative: STANDARD_NEGATIVE,
  },
  {
    id: 'martyr',
    nameZh: '殉道者',
    nameEn: 'Martyr',
    kind: 'ninja',
    phase: 'react',
    number: null,
    visualHint: '舍身、莲花、光',
    promptZh: '殉道者张开双臂以身迎向利刃，胸膛迸发出一朵由金箔与纯白流光构筑的圣洁莲花，夜空为之照亮。',
    promptEn: `${BASE_STYLE_PREFIX} Subject: A selfless martyr figure throwing open their arms to protectively absorb a mortal blow, eyes calm. From the center of the chest blooms a glowing, radiant sacred lotus flower made of kintsugi gold foil and pure white spiritual light against deep ink-wash dark. Vertical 2:3 composition.`,
    negative: STANDARD_NEGATIVE,
  },
  {
    id: 'mastermind',
    nameZh: '大将军',
    nameEn: 'Mastermind',
    kind: 'ninja',
    phase: 'reveal',
    number: null,
    visualHint: '高台、棋局、俯瞰',
    promptZh: '幕后主使大将军端坐于高阁楼台，面前是一局微缩木质将棋兵盘，手拈棋子，以全知冷峻的目光俯瞰整座城池战局。',
    promptEn: `${BASE_STYLE_PREFIX} Subject: A grand strategist mastermind seated royally upon an elevated balcony pavilion, resting a hand over a wooden battle shogi board with miniature tactical markers. Cold commanding eyes overlooking a sprawling panoramic night battlefield below. Regal gold trim. Vertical 2:3 composition.`,
    negative: STANDARD_NEGATIVE,
  },

  // ==========================================
  // 7. 仙鹤阵营 (Crane 1-5) - 配色：朱红 (vermilion red) + 金箔点缀
  // ==========================================
  {
    id: 'crane-1',
    nameZh: '仙鹤 1',
    nameEn: 'Crane 1',
    kind: 'house',
    phase: 'house',
    number: 1,
    visualHint: '仙鹤家纹、展翅丹顶、朱红与金箔',
    promptZh: '仙鹤阵营身份牌（位阶 1）：展翅腾飞的优美丹顶白鹤，底色为浓重水墨夜色，仙鹤羽翼镶嵌纯金金箔，身披朱红绸缎饰带。',
    promptEn: `${BASE_STYLE_PREFIX} Subject: House of Crane heraldic card (Rank 1). A majestic crowned crane spreading vast pristine wings, framed by swirling sumi-e night clouds. Accented with deep vermilion red silk ribbons and radiant kintsugi gold foil flecks on the plumage and royal seal. Vertical 2:3 composition.`,
    negative: STANDARD_NEGATIVE,
  },
  {
    id: 'crane-2',
    nameZh: '仙鹤 2',
    nameEn: 'Crane 2',
    kind: 'house',
    phase: 'house',
    number: 2,
    visualHint: '仙鹤武士、朱红漆甲、金羽鹤盔',
    promptZh: '仙鹤阵营身份牌（位阶 2）：身着深朱红大漆锁子甲的仙鹤武士统领，头盔缀有金箔鹤羽装饰，神威凛凛。',
    promptEn: `${BASE_STYLE_PREFIX} Subject: House of Crane noble samurai commander (Rank 2). Clad in elaborate vermilion red lacquered armor with prominent gold-foil crane crests on the helmet and pauldrons, standing resolute against an ink-wash fortress night. Vertical 2:3 composition.`,
    negative: STANDARD_NEGATIVE,
  },
  {
    id: 'crane-3',
    nameZh: '仙鹤 3',
    nameEn: 'Crane 3',
    kind: 'house',
    phase: 'house',
    number: 3,
    visualHint: '仙鹤剑客、朱红刀鞘、振翼鹤影',
    promptZh: '仙鹤阵营身份牌（位阶 3）：白衣剑客拔刀出鞘，朱红漆鞘上印有金色鹤纹，背后水墨鹤影如长虹贯日。',
    promptEn: `${BASE_STYLE_PREFIX} Subject: House of Crane graceful duelist (Rank 3). Drawing a polished curved katana from an opulent vermilion red scabbard, behind whom an ink-wash silhouette of a soaring crane spreads golden-edged wings. Vertical 2:3 composition.`,
    negative: STANDARD_NEGATIVE,
  },
  {
    id: 'crane-4',
    nameZh: '仙鹤 4',
    nameEn: 'Crane 4',
    kind: 'house',
    phase: 'house',
    number: 4,
    visualHint: '仙鹤射手、朱红羽箭、金辉鹤翎',
    promptZh: '仙鹤阵营身份牌（位阶 4）：身披红白羽衣的和弓射手挽满长弓，朱红色鹤翎箭矢闪烁金箔神光，箭指苍穹。',
    promptEn: `${BASE_STYLE_PREFIX} Subject: House of Crane master archer (Rank 4). Drawing a traditional yumi bow loaded with vermilion red fletched arrows tipped with shimmering gold foil. Elegant feathered mantle flowing in night wind. Vertical 2:3 composition.`,
    negative: STANDARD_NEGATIVE,
  },
  {
    id: 'crane-5',
    nameZh: '仙鹤 5',
    nameEn: 'Crane 5',
    kind: 'house',
    phase: 'house',
    number: 5,
    visualHint: '仙鹤守卫、朱红大旗、金印战戟',
    promptZh: '仙鹤阵营身份牌（位阶 5）：守备关隘的仙鹤铁卫紧握朱红大纛战旗，旗帜上金箔大鹤展翅欲飞，长戟如林。',
    promptEn: `${BASE_STYLE_PREFIX} Subject: House of Crane elite castle guardian (Rank 5). Gripping a towering vermilion red battle banner emblazoned with a giant gold-foil crane sigil, standing guard before a grand feudal gateway at night. Vertical 2:3 composition.`,
    negative: STANDARD_NEGATIVE,
  },

  // ==========================================
  // 8. 莲花阵营 (Lotus 1-5) - 配色：青金 (deep lapis lazuli blue) + 银白点缀
  // ==========================================
  {
    id: 'lotus-1',
    nameZh: '莲花 1',
    nameEn: 'Lotus 1',
    kind: 'house',
    phase: 'house',
    number: 1,
    visualHint: '莲花家纹、水月睡莲、青金与银白',
    promptZh: '莲花阵营身份牌（位阶 1）：在深邃水墨夜池中盛开的青金玉莲，花瓣边缘点缀纯银色反光，水波荡漾。',
    promptEn: `${BASE_STYLE_PREFIX} Subject: House of Lotus heraldic emblem card (Rank 1). A magnificent sacred water lily blooming in pristine symmetry, rendered in deep lapis lazuli blue with radiant silver-white edge highlights on dark ink-wash pond ripples. Vertical 2:3 composition.`,
    negative: STANDARD_NEGATIVE,
  },
  {
    id: 'lotus-2',
    nameZh: '莲花 2',
    nameEn: 'Lotus 2',
    kind: 'house',
    phase: 'house',
    number: 2,
    visualHint: '莲花宗师、青金道袍、银辉悬水',
    promptZh: '莲花阵营身份牌（位阶 2）：莲花宗师端坐水面之上，身着深青金丝绸道袍，周身悬浮着银白光晕的睡莲花瓣。',
    promptEn: `${BASE_STYLE_PREFIX} Subject: House of Lotus grandmaster (Rank 2). Seated cross-legged levitating above calm midnight waters, draped in flowing deep lapis lazuli silk robes with luminous silver-white lotus petals circling gracefully. Vertical 2:3 composition.`,
    negative: STANDARD_NEGATIVE,
  },
  {
    id: 'lotus-3',
    nameZh: '莲花 3',
    nameEn: 'Lotus 3',
    kind: 'house',
    phase: 'house',
    number: 3,
    visualHint: '莲花影刃、青金面纱、银色发簪',
    promptZh: '莲花阵营身份牌（位阶 3）：神秘幽雅的莲花女刺客，佩戴青金半透明面纱与银白发簪，袖中藏匿银光细刃。',
    promptEn: `${BASE_STYLE_PREFIX} Subject: House of Lotus shadowdancer (Rank 3). A poised ninja operative wearing a translucent lapis lazuli blue silk veil and polished silver hairpins, wielding concealed silver stiletto blades under moonlight. Vertical 2:3 composition.`,
    negative: STANDARD_NEGATIVE,
  },
  {
    id: 'lotus-4',
    nameZh: '莲花 4',
    nameEn: 'Lotus 4',
    kind: 'house',
    phase: 'house',
    number: 4,
    visualHint: '莲花幻术师、青金咒水、银光法符',
    promptZh: '莲花阵营身份牌（位阶 4）：幻术师催动水墨咒法，青金水雾幻化成重重莲瓣，银白法符漫天飞舞。',
    promptEn: `${BASE_STYLE_PREFIX} Subject: House of Lotus illusionist (Rank 4). Channeling arcane water mist in vibrant lapis lazuli hues forming spectral lotus blossoms, surrounded by silver-white glowing paper talismans in dark sumi-e space. Vertical 2:3 composition.`,
    negative: STANDARD_NEGATIVE,
  },
  {
    id: 'lotus-5',
    nameZh: '莲花 5',
    nameEn: 'Lotus 5',
    kind: 'house',
    phase: 'house',
    number: 5,
    visualHint: '莲花护法、青金薙刀、银丝战袍',
    promptZh: '莲花阵营身份牌（位阶 5）：手握青金长柄银刃薙刀的护法女武士，战袍绣满银色流水莲花纹，气韵沉静。',
    promptEn: `${BASE_STYLE_PREFIX} Subject: House of Lotus elite sentinel (Rank 5). Holding a ceremonial naginata polearm with a gleaming silver curved blade and lapis lazuli tassel, standing guard in quiet resolve on a misty stone bridge. Vertical 2:3 composition.`,
    negative: STANDARD_NEGATIVE,
  },

  // ==========================================
  // 9. 浪人阵营 (Ronin) - 配色：灰白 (ash grey / off-white)，无点缀
  // ==========================================
  {
    id: 'ronin',
    nameZh: '浪人',
    nameEn: 'Ronin',
    kind: 'house',
    phase: 'house',
    number: null,
    visualHint: '斗笠、破旧和服、孤身独行、灰白无点缀',
    promptZh: '浪人阵营身份牌：无主独行浪人头戴斗笠、身着褴褛灰白和服，腰佩双刀孤身行走在凄凉夜雨泥泞中，纯粹水墨灰白，无任何金银彩色点缀。',
    promptEn: `${BASE_STYLE_PREFIX} Subject: Masterless Ronin identity card. A lone wandering swordsman in a weathered conical straw hat and ragged ash-grey and off-white kimono, walking down a desolate rainy muddy road. Stark, austere sumi-e ink black and grey washes only, completely devoid of gold or color accents. Lone wolf aura. Vertical 2:3 composition.`,
    negative: STANDARD_NEGATIVE,
  },

  // ==========================================
  // 10. UI 素材 (UI Assets 1-3)
  // ==========================================
  {
    id: 'ui-lobby-bg',
    nameZh: '大厅背景底图',
    nameEn: 'Lobby Background Texture',
    kind: 'ui',
    phase: 'ui',
    number: null,
    visualHint: '水墨夜色 + 远处灯笼，中央留空给房间列表',
    promptZh: '大厅主背景底图：幽深水墨夜色全景，远景处有点点温暖纸灯笼微光与朦胧山峦，画面中央保留大面积平缓暗色留白以便承载房间列表与面板。',
    promptEn: `Sumo-e ink wash landscape painting of a serene Japanese night, deep indigo and charcoal gradients. Distant traditional lanterns glow faintly with gentle warm amber light across mist-covered hills. Wide open generous negative space in the central region reserved for clean UI overlay. Minimalist atmospheric background texture, 16:9 ratio, no text.`,
    negative: STANDARD_NEGATIVE,
  },
  {
    id: 'ui-table-texture',
    nameZh: '牌桌和纸底纹',
    nameEn: 'Table Paper Texture',
    kind: 'ui',
    phase: 'ui',
    number: null,
    visualHint: '和纸质感 + 墨渍边缘，用作桌面底纹',
    promptZh: '对局桌面底纹：高分辨率平铺和纸纹理，边缘带有自然的古雅毛边与深色水墨晕染渐变，极简典雅。',
    promptEn: `Seamless authentic Japanese handcrafted washi paper texture, subtle natural off-white mulberry fibers visible. Soft vignette of diffused black and indigo sumi-e ink stains bleeding inwards along the outer borders, clean uncluttered center, top-down flat lay, warm ambient lighting, 16:9 ratio, no text.`,
    negative: STANDARD_NEGATIVE,
  },
  {
    id: 'ui-button-primary',
    nameZh: '主要按钮质感板',
    nameEn: 'Primary Button Texture',
    kind: 'ui',
    phase: 'ui',
    number: null,
    visualHint: '霓虹描边 + 金箔底，用于主要按钮',
    promptZh: '主操作按钮材质纹理：深沉黑靛色大漆底板，边缘镶嵌纤细金箔裂纹（金缮风格）与极微弱的霓虹青蓝描边，扁平典雅。',
    promptEn: `A minimalist rectangular button surface plate texture, polished deep indigo lacquer base with fine kintsugi real gold foil fleck inlay along the beveled bevel edge and a subtle neon cyan inner stroke. Flat graphic design element for game UI, clean metallic sheen, no text.`,
    negative: STANDARD_NEGATIVE,
  },
];
